# Generated by Django 4.1.7 on 2023-03-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='member',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=200, verbose_name='密码'),
        ),
    ]
