notifications:
    email:
        recipients:
            - brilliantchanjr@gmail.com

language: node_js

node_js:
    - 16

before_script:
    - yarn install

before_deploy:
    - yarn run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
        branch: master
